In [1]:
import yfinance as yf

In [2]:
msft = yf.Ticker("MSFT")
print(msft.info)

{'zip': '98052', 'sector': 'Technology', 'longBusinessSummary': 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, and OneDrive; LinkedIn that includes Talent and marketing solutions, and subscriptions; and Dynamics 365, a set of cloud-based and on-premises business solutions for small and medium businesses, large organizations, and divisions of enterprises. Its Intelligent Cloud segment licenses SQL and Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also provides support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification to developers and IT professionals on various Microsoft products. Its More Personal Computing segment offers Windows OEM licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also provides Microsoft Surface, PC accessories, and other devices; Gaming, including Xbox hardware, and Xbox software and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through distributors and resellers; and directly through digital marketplaces, online stores, and retail stores. It has strategic partnerships with Humana Inc., Nokia, Telkomsel, Swiss Re, Kubota Corporation, FedEx Corp., and Hitachi. The company was founded in 1975 and is headquartered in Redmond, Washington.', 'city': 'Redmond', 'phone': '425-882-8080', 'state': 'WA', 'country': 'United States', 'companyOfficers': [], 'website': 'http://www.microsoft.com', 'maxAge': 1, 'address1': 'One Microsoft Way', 'fax': '425-706-7329', 'industry': 'Software—Infrastructure', 'previousClose': 202.02, 'regularMarketOpen': 202.5, 'twoHundredDayAverage': 178.6913, 'trailingAnnualDividendYield': 0.010098009, 'payoutRatio': 0.3455, 'volume24Hr': None, 'regularMarketDayHigh': 204.65, 'navPrice': None, 'averageDailyVolume10Day': 38113487, 'totalAssets': None, 'regularMarketPreviousClose': 202.02, 'fiftyDayAverage': 202.42487, 'trailingAnnualDividendRate': 2.04, 'open': 202.5, 'toCurrency': None, 'averageVolume10days': 38113487, 'expireDate': None, 'yield': None, 'algorithm': None, 'dividendRate': 2.04, 'exDividendDate': 1597795200, 'beta': 0.933333, 'circulatingSupply': None, 'startDate': None, 'regularMarketDayLow': 202.01, 'priceHint': 2, 'currency': 'USD', 'trailingPE': 35.427082, 'regularMarketVolume': 19415739, 'lastMarket': None, 'maxSupply': None, 'openInterest': None, 'marketCap': 1544938192896, 'volumeAllCurrencies': None, 'strikePrice': None, 'averageVolume': 34945826, 'priceToSalesTrailing12Months': 10.80263, 'dayLow': 202.01, 'ask': 0, 'ytdReturn': None, 'askSize': 900, 'volume': 19415739, 'fiftyTwoWeekHigh': 216.38, 'forwardPE': 27.801088, 'fromCurrency': None, 'fiveYearAvgDividendYield': 1.89, 'fiftyTwoWeekLow': 130.78, 'bid': 0, 'tradeable': False, 'dividendYield': 0.0101, 'bidSize': 800, 'dayHigh': 204.65, 'exchange': 'NMS', 'shortName': 'Microsoft Corporation', 'longName': 'Microsoft Corporation', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'isEsgPopulated': False, 'gmtOffSetMilliseconds': '-14400000', 'quoteType': 'EQUITY', 'symbol': 'MSFT', 'messageBoardId': 'finmb_21835', 'market': 'us_market', 'annualHoldingsTurnover': None, 'enterpriseToRevenue': 10.311, 'beta3Year': None, 'profitMargins': 0.30962, 'enterpriseToEbitda': 22.426, '52WeekChange': 0.47805297, 'morningStarRiskRating': None, 'forwardEps': 7.34, 'revenueQuarterlyGrowth': None, 'sharesOutstanding': 7570999808, 'fundInceptionDate': None, 'annualReportExpenseRatio': None, 'bookValue': 15.626, 'sharesShort': 39894144, 'sharesPercentSharesOut': 0.0053, 'fundFamily': None, 'lastFiscalYearEnd': 1593475200, 'heldPercentInstitutions': 0.74093, 'netIncomeToCommon': 44280999936, 'trailingEps': 5.76, 'lastDividendValue': None, 'SandP52WeekChange': 0.103224516, 'priceToBook': 13.059004, 'heldPercentInsiders': 0.014249999, 'nextFiscalYearEnd': 1656547200, 'mostRecentQuarter': 1593475200, 'shortRatio': 1.19, 'sharesShortPreviousMonthDate': 1592179200, 'floatShares': 7459706300, 'enterpriseValue': 1474596438016, 'threeYearAverageReturn': None, 'lastSplitDate': 1045526400, 'lastSplitFactor': '2:1', 'legalType': None, 'morningStarOverallRating': None, 'earningsQuarterlyGrowth': -0.151, 'dateShortInterest': 1594771200, 'pegRatio': 2.11, 'lastCapGain': None, 'shortPercentOfFloat': 0.0053, 'sharesShortPriorMonth': 42930465, 'category': None, 'fiveYearAverageReturn': None, 'regularMarketPrice': 202.5, 'logo_url': 'https://logo.clearbit.com/microsoft.com'}

In [9]:
dir(yf)

['Ticker',
 'Tickers',
 '__all__',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'base',
 'download',
 'multi',
 'pdr_override',
 'shared',
 'ticker',
 'tickers',
 'utils']

## Yahoo_fin has two modules- stock_info and options

**stock_info** has the following methods:  
>get_analysts_info()  
get_balance_sheet()  
get_cash_flow()  
get_data()  
get_day_gainers()  
get_day_losers()  
get_day_most_active()  
get_holders()  
get_income_statement()  
get_live_price()  
get_quote_table()  
get_top_crypto()  
get_stats()  
get_stats_valuation()  
tickers_dow()  
tickers_nasdaq()  
tickers_other()  
tickers_sp500()  

**Options** has the following methods::
>get_calls()  
get_expiration_dates()  
get_options_chain()  
get_puts()  

There are the methods you can’t use without requests_html are:  
>#### stock_info module
get_day_gainers()  
get_day_most_active()  
get_day_losers()  
get_top_crypto()  
>#### options module  
get_expiration_dates()

## How do I download historical data using the Yahoo Finance API?

Historical price data is the one thing we will probably almost always need. The method to get this in the Yahoo_fin library is **get_data()**

In [12]:
from yahoo_fin.stock_info import get_data

It takes the arguments:  
>• ticker: case insensitive ticker of the desired stock/bond  
• start_date: date you want the data to start from (mm/dd/yyyy)  
• end_date: date you want the data to end (mm/dd/yyyy)  
• index_as_date: {True, False}. Default is true. If true then the dates of the records are set as the index, else they are returned as a separate column.  
• interval: {“1d”, “1wk”, “1mo”}. Refers to the interval to sample the data: “1d”= daily, “1wk”= weekly, “1mo”=monthly.

In [14]:
help(get_data)

Help on function get_data in module yahoo_fin.stock_info:

get_data(ticker, start_date=None, end_date=None, index_as_date=True, interval='1d')
    Downloads historical stock price data into a pandas data frame.  Interval
    must be "1d", "1wk", or "1mo" for daily, weekly, or monthly data.

    @param: ticker
    @param: start_date = None
    @param: end_date = None
    @param: index_as_date = True
    @param: interval = "1d"

In [15]:
# Amazon Weekly Charts
amazon_weekly= get_data("amzn", start_date="12/04/2009", end_date="12/04/2019", index_as_date = True, interval="1wk")
amazon_weekly

,open,high,low,close,adjclose,volume,ticker
2009-11-30,143.619995,145.910004,135.110001,137.580002,137.580002,31350900,AMZN
2009-12-07,138.000000,139.000000,129.820007,134.149994,134.149994,47863000,AMZN
2009-12-14,132.500000,132.610001,125.650002,128.479996,128.479996,45794900,AMZN
2009-12-21,130.479996,139.699997,130.190002,138.470001,138.470001,32406000,AMZN
2009-12-28,139.750000,142.580002,134.520004,134.520004,134.520004,28600700,AMZN
...,...,...,...,...,...,...,...
2019-11-04,1801.010010,1815.060059,1774.040039,1785.880005,1785.880005,11461600,AMZN
2019-11-11,1778.000000,1786.219971,1732.859985,1739.489990,1739.489990,13165500,AMZN
2019-11-18,1738.300049,1762.520020,1722.709961,1745.719971,1745.719971,13042300,AMZN
2019-11-25,1753.250000,1824.689941,1753.239990,1800.800049,1800.800049,11616400,AMZN
2019-12-02,1804.400024,1805.550049,1747.229980,1769.959961,1769.959961,7306500,AMZN

In [16]:
# Multiple Stocks
ticker_list = ["amzn", "aapl", "ba"]
historical_datas = {}
for ticker in ticker_list:
    historical_datas[ticker] = get_data(ticker)

In [18]:
historical_datas['aapl']

,open,high,low,close,adjclose,volume,ticker
1980-12-12,0.513393,0.515625,0.513393,0.513393,0.405683,117258400.0,AAPL
1980-12-15,0.488839,0.488839,0.486607,0.486607,0.384517,43971200.0,AAPL
1980-12-16,0.453125,0.453125,0.450893,0.450893,0.356296,26432000.0,AAPL
1980-12-17,0.462054,0.464286,0.462054,0.462054,0.365115,21610400.0,AAPL
1980-12-18,0.475446,0.477679,0.475446,0.475446,0.375698,18362400.0,AAPL
...,...,...,...,...,...,...,...
2020-07-23,387.989990,388.309998,368.040009,371.380005,371.380005,49251100.0,AAPL
2020-07-24,363.950012,371.880005,356.579987,370.459991,370.459991,46359700.0,AAPL
2020-07-27,374.839996,379.619995,373.920013,379.239990,379.239990,30303500.0,AAPL
2020-07-28,377.470001,378.200012,372.989990,373.010010,373.010010,25906400.0,AAPL
2020-07-29,375.000000,380.920013,374.850006,380.160004,380.160004,22500400.0,AAPL

For instance tickers_dow() returns a list of all the tickers in the Dow Jones so we can do:

In [19]:
import yahoo_fin.stock_info as si

In [20]:
dow_list = si.tickers_dow()

In [21]:
print("Tickers in Dow Jones:", len(dow_list))
dow_list[0:10]

Tickers in Dow Jones: 30

['AAPL', 'AXP', 'BA', 'CAT', 'CSCO', 'CVX', 'DIS', 'DOW', 'GS', 'HD']

In [22]:
#Iterate through the list of tickers, appending each time to thedictionary again:
dow_historical = {}
for ticker in dow_list:
    dow_historical[ticker] = si.get_data(ticker, start_date="01/01/2020",\
                                         end_date="01/03/2020", interval="1d")
dow_historical

{'AAPL':                  open        high         low       close    adjclose  \
 2020-01-02  296.23999  300.600006  295.190002  300.350006  298.829956

               volume ticker
 2020-01-02  33870100   AAPL  ,
 'AXP':                   open        high         low       close    adjclose  \
 2020-01-02  124.660004  126.269997  124.230003  125.849998  124.589485

              volume ticker
 2020-01-02  2708000    AXP  ,
 'BA':                   open        high         low       close    adjclose  \
 2020-01-02  328.549988  333.350006  327.700012  333.320007  331.348572

              volume ticker
 2020-01-02  4544400     BA  ,
 'CAT':              open        high         low       close    adjclose   volume  \
 2020-01-02  149.0  150.550003  147.979996  150.529999  147.020508  3311900

            ticker
 2020-01-02    CAT  ,
 'CSCO':                  open       high        low      close  adjclose    volume  \
 2020-01-02  48.060001  48.419998  47.880001  48.419998  47.59034  16708100

            ticker
 2020-01-02   CSCO  ,
 'CVX':                   open        high         low   close    adjclose   volume  \
 2020-01-02  120.809998  121.629997  120.769997  121.43  118.290535  5205000

            ticker
 2020-01-02    CVX  ,
 'DIS':                   open        high         low       close    adjclose  \
 2020-01-02  145.289993  148.199997  145.100006  148.199997  148.199997

              volume ticker
 2020-01-02  9502100    DIS  ,
 'DOW':              open       high        low  close   adjclose   volume ticker
 2020-01-02  55.23  55.540001  53.639999  53.75  51.946507  5145200    DOW,
 'GS':              open        high         low       close    adjclose   volume  \
 2020-01-02  231.0  234.639999  230.160004  234.320007  231.449234  3736300

            ticker
 2020-01-02     GS  ,
 'HD':                   open        high         low       close    adjclose  \
 2020-01-02  219.080002  219.759995  217.839996  219.660004  216.904984

              volume ticker
 2020-01-02  3935700     HD  ,
 'IBM':              open        high         low       close    adjclose   volume  \
 2020-01-02  135.0  135.919998  134.770004  135.419998  132.246933  3148600

            ticker
 2020-01-02    IBM  ,
 'INTC':                  open       high        low  close   adjclose    volume ticker
 2020-01-02  60.240002  60.970001  60.220001  60.84  60.201786  18056000   INTC,
 'JNJ':                   open        high         low       close    adjclose  \
 2020-01-02  145.869995  146.020004  145.080002  145.970001  144.046555

              volume ticker
 2020-01-02  5777000    JNJ  ,
 'JPM':                   open        high         low       close    adjclose  \
 2020-01-02  139.789993  141.100006  139.259995  141.089996  137.409225

               volume ticker
 2020-01-02  10803700    JPM  ,
 'KO':              open   high        low      close   adjclose    volume ticker
 2020-01-02  55.32  55.43  54.759998  54.990002  54.021152  11867700     KO,
 'MCD':              open        high         low       close    adjclose   volume  \
 2020-01-02  198.0  200.800003  197.809998  200.789993  198.219696  3554200

            ticker
 2020-01-02    MCD  ,
 'MMM':                   open        high         low  close    adjclose   volume  \
 2020-01-02  177.679993  180.009995  177.139999  180.0  176.632721  3601700

            ticker
 2020-01-02    MMM  ,
 'MRK':                  open       high        low      close   adjclose   volume  \
 2020-01-02  91.080002  92.139999  90.370003  92.040001  90.565979  7873500

            ticker
 2020-01-02    MRK  ,
 'MSFT':                   open        high         low       close    adjclose  \
 2020-01-02  158.779999  160.729996  158.330002  160.619995  159.737595

               volume ticker
 2020-01-02  22622100   MSFT  ,
 'NKE':                   open        high         low       close    adjclose  \
 2020-01-02  101.360001  102.209999  101.019997  102.199997  101.663628

              volume ticker
 2020-01-02  5644100    NKE  ,
 'PFE':                  open       high        low      close   adjclose    volume  \
 2020-01-02  39.299999  39.349998  38.880001  39.139999  37.990608  15668000

            ticker
 2020-01-02    PFE  ,
 'PG':              open        high         low       close    adjclose   volume  \
 2020-01-02  124.5  124.730003  122.940002  123.410004  121.104179  8130800

            ticker
 2020-01-02     PG  ,
 'RTX':                  open       high        low      close   adjclose   volume  \
 2020-01-02  94.235367  96.425423  94.235367  96.375076  95.076424  2801500

            ticker
 2020-01-02    RTX  ,
 'TRV':                   open        high         low       close    adjclose  \
 2020-01-02  137.520004  137.740005  136.139999  137.509995  135.699615

              volume ticker
 2020-01-02  1117300    TRV  ,
 'UNH':                   open        high         low  close    adjclose   volume  \
 2020-01-02  293.980011  295.700012  289.790009  292.5  289.989502  2543400

            ticker
 2020-01-02    UNH  ,
 'V':              open        high         low       close    adjclose   volume  \
 2020-01-02  189.0  191.139999  188.720001  191.119995  190.524582  8733000

            ticker
 2020-01-02      V  ,
 'VZ':                  open       high        low      close  adjclose    volume  \
 2020-01-02  61.380001  61.450001  60.810001  61.049999  59.11446  11447900

            ticker
 2020-01-02     VZ  ,
 'WBA':                  open   high        low      close   adjclose   volume ticker
 2020-01-02  59.279999  59.59  58.700001  59.080002  57.911522  5700500    WBA,
 'WMT':                   open        high         low       close   adjclose  \
 2020-01-02  118.860001  119.889999  118.699997  118.940002  117.89743

              volume ticker
 2020-01-02  6764900    WMT  ,
 'XOM':                  open       high        low      close  adjclose    volume  \
 2020-01-02  70.239998  71.019997  70.239998  70.900002  68.56707  12456400

            ticker
 2020-01-02    XOM  }

### How do I download fundamental data?

With Yahoo_fin there are often a few ways to get the same bit of data with different methods calls. Let’s try grabbing a few different bits of fundamentals data.

#### Price to Earnings Ratio
> The easiest way to get the Price to Earnings (P/E) ratio for a stock is with the get_quote_table() function.  
<b>*Note*</b> many of the methods that follow automatically return the data in a pandas dataframe.

**get_quote_table()** doesn’t do this by default but takes an optional dict_result parameter that when set to False also makes the method return a pandas data-frame (instead of a dictionary).

In [23]:
quote_table = si.get_quote_table("aapl", dict_result=False)
quote_table

                   attribute            value
0              1y Target Est           371.96
1              52 Week Range  192.58 - 399.82
2                        Ask      0.00 x 1000
3                Avg. Volume      3.45975e+07
4          Beta (5Y Monthly)             1.18
5                        Bid      0.00 x 3000
6                Day's Range  374.85 - 380.92
7                  EPS (TTM)            12.73
8              Earnings Date     Jul 30, 2020
9           Ex-Dividend Date     May 08, 2020
10  Forward Dividend & Yield     3.28 (0.88%)
11                Market Cap           1.648T
12                      Open              375
13            PE Ratio (TTM)            29.87
14            Previous Close           373.01
15               Quote Price           380.16
16                    Volume      2.25823e+07

In [24]:
# Stats Table
stats_table=si.get_stats_valuation("aapl")
stats_table

,Unnamed: 0,As of Date: 7/29/2020Current,3/31/2020,12/31/2019,9/30/2019,6/30/2019
0,Market Cap (intraday) 5,1.62T,1.10T,1.29T,995.15B,910.64B
1,Enterprise Value 3,1.63T,1.10T,1.30T,1.01T,943.18B
2,Trailing P/E,29.16,20.02,24.70,19.01,16.58
3,Forward P/E 1,24.63,19.65,22.17,17.27,15.97
4,PEG Ratio (5 yr expected) 1,2.05,1.58,2.03,2.04,1.45
5,Price/Sales (ttm),6.26,4.34,5.25,4.09,3.68
6,Price/Book (mrq),20.62,12.28,14.23,10.32,8.47
7,Enterprise Value/Revenue 3,6.09,18.88,14.11,15.76,17.53
8,Enterprise Value/EBITDA 6,19.90,66.00,43.87,50.16,60.04

In [25]:
#Dividends
quote_table = si.get_quote_table("aapl")
quote_table["Forward Dividend & Yield"]

'3.28 (0.88%)'

### Fundamentals data with multiple tickers at once
Lets have a go at grabbing fundamentals data for a list of tickers at once, and then have a go at picking out a single attribute we want to rank all stocks by.

In [26]:
import pandas as pd
# get list of Dow tickers
dow_list = si.tickers_dow()

In [27]:
dow_stats = {}
for ticker in dow_list:
    temp = si.get_stats_valuation(ticker)
    temp = temp.iloc[:,:2]
    temp.columns = ["Attribute", "Recent"]
    dow_stats[ticker] = temp
dow_stats

{'AAPL':                      Attribute Recent
 0      Market Cap (intraday) 5  1.62T
 1           Enterprise Value 3  1.63T
 2                 Trailing P/E  29.16
 3                Forward P/E 1  24.63
 4  PEG Ratio (5 yr expected) 1   2.05
 5            Price/Sales (ttm)   6.26
 6             Price/Book (mrq)  20.62
 7   Enterprise Value/Revenue 3   6.09
 8    Enterprise Value/EBITDA 6  19.90,
 'AXP':                      Attribute  Recent
 0      Market Cap (intraday) 5  77.13B
 1           Enterprise Value 3     NaN
 2                 Trailing P/E   19.83
 3                Forward P/E 1   20.53
 4  PEG Ratio (5 yr expected) 1    1.84
 5            Price/Sales (ttm)    2.64
 6             Price/Book (mrq)    3.66
 7   Enterprise Value/Revenue 3     NaN
 8    Enterprise Value/EBITDA 6     NaN,
 'BA':                      Attribute   Recent
 0      Market Cap (intraday) 5   96.05B
 1           Enterprise Value 3  119.45B
 2                 Trailing P/E      NaN
 3                Forward P/E 1    40.16
 4  PEG Ratio (5 yr expected) 1     5.91
 5            Price/Sales (ttm)     1.36
 6             Price/Book (mrq)      NaN
 7   Enterprise Value/Revenue 3     1.69
 8    Enterprise Value/EBITDA 6   -40.80,
 'CAT':                      Attribute   Recent
 0      Market Cap (intraday) 5   74.71B
 1           Enterprise Value 3  104.68B
 2                 Trailing P/E    14.58
 3                Forward P/E 1    27.62
 4  PEG Ratio (5 yr expected) 1     7.98
 5            Price/Sales (ttm)     1.52
 6             Price/Book (mrq)     5.26
 7   Enterprise Value/Revenue 3     2.05
 8    Enterprise Value/EBITDA 6    10.42,
 'CSCO':                      Attribute   Recent
 0      Market Cap (intraday) 5  195.91B
 1           Enterprise Value 3  183.42B
 2                 Trailing P/E    18.34
 3                Forward P/E 1    15.17
 4  PEG Ratio (5 yr expected) 1     2.90
 5            Price/Sales (ttm)     3.91
 6             Price/Book (mrq)     5.49
 7   Enterprise Value/Revenue 3     3.63
 8    Enterprise Value/EBITDA 6    10.88,
 'CVX':                      Attribute   Recent
 0      Market Cap (intraday) 5  168.16B
 1           Enterprise Value 3  191.97B
 2                 Trailing P/E    43.30
 3                Forward P/E 1   555.56
 4  PEG Ratio (5 yr expected) 1    14.21
 5            Price/Sales (ttm)     1.25
 6             Price/Book (mrq)     1.17
 7   Enterprise Value/Revenue 3     1.42
 8    Enterprise Value/EBITDA 6     5.35,
 'DIS':                      Attribute   Recent
 0      Market Cap (intraday) 5  208.82B
 1           Enterprise Value 3  249.93B
 2                 Trailing P/E    50.48
 3                Forward P/E 1    37.59
 4  PEG Ratio (5 yr expected) 1    10.40
 5            Price/Sales (ttm)     2.68
 6             Price/Book (mrq)     2.31
 7   Enterprise Value/Revenue 3     3.20
 8    Enterprise Value/EBITDA 6    18.10,
 'DOW':                      Attribute  Recent
 0      Market Cap (intraday) 5  31.58B
 1           Enterprise Value 3  47.40B
 2                 Trailing P/E     NaN
 3                Forward P/E 1   40.32
 4  PEG Ratio (5 yr expected) 1     NaN
 5            Price/Sales (ttm)    0.81
 6             Price/Book (mrq)    2.52
 7   Enterprise Value/Revenue 3    1.21
 8    Enterprise Value/EBITDA 6   21.54,
 'GS':                      Attribute  Recent
 0      Market Cap (intraday) 5  69.66B
 1           Enterprise Value 3     NaN
 2                 Trailing P/E   10.74
 3                Forward P/E 1   12.14
 4  PEG Ratio (5 yr expected) 1    2.64
 5            Price/Sales (ttm)    2.02
 6             Price/Book (mrq)    0.76
 7   Enterprise Value/Revenue 3     NaN
 8    Enterprise Value/EBITDA 6     NaN,
 'HD':                      Attribute   Recent
 0      Market Cap (intraday) 5  285.35B
 1           Enterprise Value 3  318.40B
 2                 Trailing P/E    26.37
 3                Forward P/E 1    26.39
 4  PEG Ratio (5 yr expected) 1     3.61
 5            Price/Sales (ttm)     2.58
 6             Price/Book (mrq)      NaN
 7   Enterprise Value/Revenue 3     2.84
 8    Enterprise Value/EBITDA 6    17.74,
 'IBM':                      Attribute   Recent
 0      Market Cap (intraday) 5  110.52B
 1           Enterprise Value 3  166.18B
 2                 Trailing P/E    14.11
 3                Forward P/E 1    11.20
 4  PEG Ratio (5 yr expected) 1     8.68
 5            Price/Sales (ttm)     1.47
 6             Price/Book (mrq)     5.38
 7   Enterprise Value/Revenue 3     2.20
 8    Enterprise Value/EBITDA 6    11.00,
 'INTC':                      Attribute   Recent
 0      Market Cap (intraday) 5  210.82B
 1           Enterprise Value 3  223.35B
 2                 Trailing P/E     9.15
 3                Forward P/E 1    10.95
 4  PEG Ratio (5 yr expected) 1     1.81
 5            Price/Sales (ttm)     2.73
 6             Price/Book (mrq)     2.57
 7   Enterprise Value/Revenue 3     2.83
 8    Enterprise Value/EBITDA 6     5.64,
 'JNJ':                      Attribute   Recent
 0      Market Cap (intraday) 5  386.58B
 1           Enterprise Value 3  397.84B
 2                 Trailing P/E    25.80
 3                Forward P/E 1    18.59
 4  PEG Ratio (5 yr expected) 1     3.60
 5            Price/Sales (ttm)     4.87
 6             Price/Book (mrq)     6.14
 7   Enterprise Value/Revenue 3     4.94
 8    Enterprise Value/EBITDA 6    16.91,
 'JPM':                      Attribute   Recent
 0      Market Cap (intraday) 5  295.31B
 1           Enterprise Value 3      NaN
 2                 Trailing P/E    13.04
 3                Forward P/E 1    17.12
 4  PEG Ratio (5 yr expected) 1     7.78
 5            Price/Sales (ttm)     2.56
 6             Price/Book (mrq)     1.26
 7   Enterprise Value/Revenue 3      NaN
 8    Enterprise Value/EBITDA 6      NaN,
 'KO':                      Attribute   Recent
 0      Market Cap (intraday) 5  206.95B
 1           Enterprise Value 3  239.47B
 2                 Trailing P/E    22.73
 3                Forward P/E 1    25.84
 4  PEG Ratio (5 yr expected) 1     4.71
 5            Price/Sales (ttm)     6.07
 6             Price/Book (mrq)    11.84
 7   Enterprise Value/Revenue 3     6.98
 8    Enterprise Value/EBITDA 6    18.19,
 'MCD':                      Attribute   Recent
 0      Market Cap (intraday) 5  145.89B
 1           Enterprise Value 3  192.82B
 2                 Trailing P/E    31.10
 3                Forward P/E 1    33.78
 4  PEG Ratio (5 yr expected) 1     5.06
 5            Price/Sales (ttm)     7.69
 6             Price/Book (mrq)      NaN
 7   Enterprise Value/Revenue 3    10.01
 8    Enterprise Value/EBITDA 6    25.93,
 'MMM':                      Attribute   Recent
 0      Market Cap (intraday) 5   90.00B
 1           Enterprise Value 3  107.15B
 2                 Trailing P/E    17.74
 3                Forward P/E 1    19.30
 4  PEG Ratio (5 yr expected) 1     4.76
 5            Price/Sales (ttm)     2.90
 6             Price/Book (mrq)     8.29
 7   Enterprise Value/Revenue 3     3.42
 8    Enterprise Value/EBITDA 6    12.40,
 'MRK':                      Attribute   Recent
 0      Market Cap (intraday) 5  194.61B
 1           Enterprise Value 3  215.17B
 2                 Trailing P/E    19.52
 3                Forward P/E 1    14.56
 4  PEG Ratio (5 yr expected) 1     1.61
 5            Price/Sales (ttm)     4.11
 6             Price/Book (mrq)     7.43
 7   Enterprise Value/Revenue 3     4.48
 8    Enterprise Value/EBITDA 6    12.88,
 'MSFT':                      Attribute Recent
 0      Market Cap (intraday) 5  1.54T
 1           Enterprise Value 3  1.48T
 2                 Trailing P/E  35.43
 3                Forward P/E 1  31.25
 4  PEG Ratio (5 yr expected) 1   2.43
 5            Price/Sales (ttm)  10.96
 6             Price/Book (mrq)  13.06
 7   Enterprise Value/Revenue 3  10.34
 8    Enterprise Value/EBITDA 6  22.50,
 'NKE':                      Attribute   Recent
 0      Market Cap (intraday) 5  153.06B
 1           Enterprise Value 3  157.29B
 2                 Trailing P/E    61.52
 3                Forward P/E 1    39.22
 4  PEG Ratio (5 yr expected) 1     4.49
 5            Price/Sales (ttm)     4.19
 6             Price/Book (mrq)    19.00
 7   Enterprise Value/Revenue 3     4.21
 8    Enterprise Value/EBITDA 6    50.49,
 'PFE':                      Attribute   Recent
 0      Market Cap (intraday) 5  218.08B
 1           Enterprise Value 3  260.04B
 2                 Trailing P/E    15.52
 3                Forward P/E 1    13.87
 4  PEG Ratio (5 yr expected) 1     2.81
 5            Price/Sales (ttm)     4.49
 6             Price/Book (mrq)     3.35
 7   Enterprise Value/Revenue 3     5.29
 8    Enterprise Value/EBITDA 6    11.47,
 'PG':                      Attribute   Recent
 0      Market Cap (intraday) 5  311.83B
 1           Enterprise Value 3  333.35B
 2                 Trailing P/E    68.46
 3                Forward P/E 1    24.04
 4  PEG Ratio (5 yr expected) 1     3.21
 5            Price/Sales (ttm)     4.56
 6             Price/Book (mrq)     6.99
 7   Enterprise Value/Revenue 3     4.74
 8    Enterprise Value/EBITDA 6    31.02,
 'RTX':                      Attribute   Recent
 0      Market Cap (intraday) 5   90.00B
 1           Enterprise Value 3  117.50B
 2                 Trailing P/E    19.73
 3                Forward P/E 1    16.78
 4  PEG Ratio (5 yr expected) 1     1.97
 5            Price/Sales (ttm)     0.96
 6             Price/Book (mrq)     1.34
 7   Enterprise Value/Revenue 3     1.82
 8    Enterprise Value/EBITDA 6    17.90,
 'TRV':                      Attribute  Recent
 0      Market Cap (intraday) 5  29.59B
 1           Enterprise Value 3  36.01B
 2                 Trailing P/E   16.62
 3                Forward P/E 1   12.79
 4  PEG Ratio (5 yr expected) 1    1.21
 5            Price/Sales (ttm)    0.96
 6             Price/Book (mrq)    1.10
 7   Enterprise Value/Revenue 3    1.15
 8    Enterprise Value/EBITDA 6     NaN,
 'UNH':                      Attribute   Recent
 0      Market Cap (intraday) 5  290.85B
 1           Enterprise Value 3  311.31B
 2                 Trailing P/E    17.24
 3                Forward P/E 1    18.76
 4  PEG Ratio (5 yr expected) 1     1.49
 5            Price/Sales (ttm)     1.20
 6             Price/Book (mrq)     4.37
 7   Enterprise Value/Revenue 3     1.26
 8    Enterprise Value/EBITDA 6    11.44,
 'V':                      Attribute   Recent
 0      Market Cap (intraday) 5  432.16B
 1           Enterprise Value 3  443.36B
 2                 Trailing P/E    35.38
 3                Forward P/E 1    33.22
 4  PEG Ratio (5 yr expected) 1     2.44
 5            Price/Sales (ttm)    18.50
 6             Price/Book (mrq)    14.38
 7   Enterprise Value/Revenue 3    18.56
 8    Enterprise Value/EBITDA 6    26.79,
 'VZ':                      Attribute   Recent
 0      Market Cap (intraday) 5  235.25B
 1           Enterprise Value 3  367.38B
 2                 Trailing P/E    12.83
 3                Forward P/E 1    11.83
 4  PEG Ratio (5 yr expected) 1     3.95
 5            Price/Sales (ttm)     1.79
 6             Price/Book (mrq)     3.91
 7   Enterprise Value/Revenue 3     2.83
 8    Enterprise Value/EBITDA 6     8.45,
 'WBA':                      Attribute  Recent
 0      Market Cap (intraday) 5  35.67B
 1           Enterprise Value 3  75.62B
 2                 Trailing P/E   48.42
 3                Forward P/E 1    8.00
 4  PEG Ratio (5 yr expected) 1    6.89
 5            Price/Sales (ttm)    0.26
 6             Price/Book (mrq)    1.72
 7   Enterprise Value/Revenue 3    0.55
 8    Enterprise Value/EBITDA 6   21.34,
 'WMT':                      Attribute   Recent
 0      Market Cap (intraday) 5  371.67B
 1           Enterprise Value 3  432.17B
 2                 Trailing P/E    24.95
 3                Forward P/E 1    26.04
 4  PEG Ratio (5 yr expected) 1     4.08
 5            Price/Sales (ttm)     0.70
 6             Price/Book (mrq)     5.45
 7   Enterprise Value/Revenue 3     0.81
 8    Enterprise Value/EBITDA 6    12.73,
 'XOM':                      Attribute   Recent
 0      Market Cap (intraday) 5  186.44B
 1           Enterprise Value 3  234.64B
 2                 Trailing P/E    16.51
 3                Forward P/E 1   121.95
 4  PEG Ratio (5 yr expected) 1    10.47
 5            Price/Sales (ttm)     0.76
 6             Price/Book (mrq)     1.02
 7   Enterprise Value/Revenue 3     0.94
 8    Enterprise Value/EBITDA 6     6.40}

In [28]:
#Now we combine all of these dataframes into a single dataframe:
combined_stats = pd.concat(dow_stats)
combined_stats = combined_stats.reset_index()
combined_stats

    level_0  level_1                    Attribute Recent
0      AAPL        0      Market Cap (intraday) 5  1.62T
1      AAPL        1           Enterprise Value 3  1.63T
2      AAPL        2                 Trailing P/E  29.16
3      AAPL        3                Forward P/E 1  24.63
4      AAPL        4  PEG Ratio (5 yr expected) 1   2.05
..      ...      ...                          ...    ...
265     XOM        4  PEG Ratio (5 yr expected) 1  10.47
266     XOM        5            Price/Sales (ttm)   0.76
267     XOM        6             Price/Book (mrq)   1.02
268     XOM        7   Enterprise Value/Revenue 3   0.94
269     XOM        8    Enterprise Value/EBITDA 6   6.40

[270 rows x 4 columns]

In [29]:
#And delete the unnecessary “level_1” column and clean up the renaming column names:
del combined_stats["level_1"]

In [30]:
# update column names
combined_stats.columns = ["Ticker", "Attribute", "Recent"]
combined_stats

    Ticker                    Attribute Recent
0     AAPL      Market Cap (intraday) 5  1.62T
1     AAPL           Enterprise Value 3  1.63T
2     AAPL                 Trailing P/E  29.16
3     AAPL                Forward P/E 1  24.63
4     AAPL  PEG Ratio (5 yr expected) 1   2.05
..     ...                          ...    ...
265    XOM  PEG Ratio (5 yr expected) 1  10.47
266    XOM            Price/Sales (ttm)   0.76
267    XOM             Price/Book (mrq)   1.02
268    XOM   Enterprise Value/Revenue 3   0.94
269    XOM    Enterprise Value/EBITDA 6   6.40

[270 rows x 3 columns]

In [31]:
print(type(combined_stats))

<class 'pandas.core.frame.DataFrame'>

In [34]:
# Comparing by a particular attribute
pe_ratios = combined_stats[combined_stats["Attribute"]=="Trailing P/E"].reset_index()
pe_ratios

    index Ticker     Attribute Recent
0       2   AAPL  Trailing P/E  29.16
1      11    AXP  Trailing P/E  19.83
2      20     BA  Trailing P/E    NaN
3      29    CAT  Trailing P/E  14.58
4      38   CSCO  Trailing P/E  18.34
5      47    CVX  Trailing P/E  43.30
6      56    DIS  Trailing P/E  50.48
7      65    DOW  Trailing P/E    NaN
8      74     GS  Trailing P/E  10.74
9      83     HD  Trailing P/E  26.37
10     92    IBM  Trailing P/E  14.11
11    101   INTC  Trailing P/E   9.15
12    110    JNJ  Trailing P/E  25.80
13    119    JPM  Trailing P/E  13.04
14    128     KO  Trailing P/E  22.73
15    137    MCD  Trailing P/E  31.10
16    146    MMM  Trailing P/E  17.74
17    155    MRK  Trailing P/E  19.52
18    164   MSFT  Trailing P/E  35.43
19    173    NKE  Trailing P/E  61.52
20    182    PFE  Trailing P/E  15.52
21    191     PG  Trailing P/E  68.46
22    200    RTX  Trailing P/E  19.73
23    209    TRV  Trailing P/E  16.62
24    218    UNH  Trailing P/E  17.24
25    227      V  Trailing P/E  35.38
26    236     VZ  Trailing P/E  12.83
27    245    WBA  Trailing P/E  48.42
28    254    WMT  Trailing P/E  24.95
29    263    XOM  Trailing P/E  16.51

In [35]:
#we can order the ‘Recent’ column to find the best/worst earners:
pe_ratios_sorted = pe_ratios.sort_values('Recent',ascending=False)
pe_ratios_sorted

    index Ticker     Attribute Recent
11    101   INTC  Trailing P/E   9.15
21    191     PG  Trailing P/E  68.46
19    173    NKE  Trailing P/E  61.52
6      56    DIS  Trailing P/E  50.48
27    245    WBA  Trailing P/E  48.42
5      47    CVX  Trailing P/E  43.30
18    164   MSFT  Trailing P/E  35.43
25    227      V  Trailing P/E  35.38
15    137    MCD  Trailing P/E  31.10
0       2   AAPL  Trailing P/E  29.16
9      83     HD  Trailing P/E  26.37
12    110    JNJ  Trailing P/E  25.80
28    254    WMT  Trailing P/E  24.95
14    128     KO  Trailing P/E  22.73
1      11    AXP  Trailing P/E  19.83
22    200    RTX  Trailing P/E  19.73
17    155    MRK  Trailing P/E  19.52
4      38   CSCO  Trailing P/E  18.34
16    146    MMM  Trailing P/E  17.74
24    218    UNH  Trailing P/E  17.24
23    209    TRV  Trailing P/E  16.62
29    263    XOM  Trailing P/E  16.51
20    182    PFE  Trailing P/E  15.52
3      29    CAT  Trailing P/E  14.58
10     92    IBM  Trailing P/E  14.11
13    119    JPM  Trailing P/E  13.04
26    236     VZ  Trailing P/E  12.83
8      74     GS  Trailing P/E  10.74
2      20     BA  Trailing P/E    NaN
7      65    DOW  Trailing P/E    NaN

### How do I download trading data?
Remember, you can get the historical open, high, low, close, volume data sampled at regular intervals from the get_data() method:

In [36]:
si.get_data('aapl')

,open,high,low,close,adjclose,volume,ticker
1980-12-12,0.513393,0.515625,0.513393,0.513393,0.405683,117258400.0,AAPL
1980-12-15,0.488839,0.488839,0.486607,0.486607,0.384517,43971200.0,AAPL
1980-12-16,0.453125,0.453125,0.450893,0.450893,0.356296,26432000.0,AAPL
1980-12-17,0.462054,0.464286,0.462054,0.462054,0.365115,21610400.0,AAPL
1980-12-18,0.475446,0.477679,0.475446,0.475446,0.375698,18362400.0,AAPL
...,...,...,...,...,...,...,...
2020-07-23,387.989990,388.309998,368.040009,371.380005,371.380005,49251100.0,AAPL
2020-07-24,363.950012,371.880005,356.579987,370.459991,370.459991,46359700.0,AAPL
2020-07-27,374.839996,379.619995,373.920013,379.239990,379.239990,30303500.0,AAPL
2020-07-28,377.470001,378.200012,372.989990,373.010010,373.010010,25906400.0,AAPL
2020-07-29,375.000000,380.920013,374.850006,380.160004,380.160004,22500400.0,AAPL

In [37]:
si.get_quote_table("aapl")

{'1y Target Est': 371.96,
 '52 Week Range': '192.58 - 399.82',
 'Ask': '0.00 x 1000',
 'Avg. Volume': 34597506.0,
 'Beta (5Y Monthly)': 1.18,
 'Bid': '0.00 x 3000',
 "Day's Range": '374.85 - 380.92',
 'EPS (TTM)': 12.73,
 'Earnings Date': 'Jul 30, 2020',
 'Ex-Dividend Date': 'May 08, 2020',
 'Forward Dividend & Yield': '3.28 (0.88%)',
 'Market Cap': '1.648T',
 'Open': 375.0,
 'PE Ratio (TTM)': 29.87,
 'Previous Close': 373.01,
 'Quote Price': 380.1600036621094,
 'Volume': 22582314.0}

In [38]:
#Market Cap
si.get_quote_table("aapl")["Market Cap"]

'1.648T'

In [39]:
# Highs and Lows
si.get_quote_table("aapl")["Day's Range"]

'374.85 - 380.92'

In [40]:
daily_range = si.get_quote_table("aapl")["Day's Range"]
daily_low = float(daily_range.split(" - ")[0])
daily_high = float(daily_range.split(" - ")[1])
print("daily low:", daily_low)
print("daily high:", daily_high)

daily low: 374.85
daily high: 380.92

### How do I download data from the Income Statement?
Yahoo_fin has a fantastically useful **get_income_statement()** function that does this all in one for us:

In [41]:
income_statement = si.get_income_statement("aapl")
income_statement

endDate,2019-09-28,2018-09-29,2017-09-30,2016-09-24
Breakdown,,,,
researchDevelopment,16217000000,14236000000,11581000000,10045000000
effectOfAccountingCharges,None,None,None,None
incomeBeforeTax,65737000000,72903000000,64089000000,61372000000
minorityInterest,None,None,None,None
netIncome,55256000000,59531000000,48351000000,45687000000
sellingGeneralAdministrative,18245000000,16705000000,15261000000,14194000000
grossProfit,98392000000,101839000000,88186000000,84263000000
ebit,63930000000,70898000000,61344000000,60024000000
operatingIncome,63930000000,70898000000,61344000000,60024000000
otherOperatingExpenses,None,None,None,None
interestExpense,-3576000000,-3240000000,-2323000000,-1456000000
extraordinaryItems,None,None,None,None
nonRecurring,None,None,None,None
otherItems,None,None,None,None
incomeTaxExpense,10481000000,13372000000,15738000000,15685000000
totalRevenue,260174000000,265595000000,229234000000,215639000000
totalOperatingExpenses,196244000000,194697000000,167890000000,155615000000
costOfRevenue,161782000000,163756000000,141048000000,131376000000
totalOtherIncomeExpenseNet,1807000000,2005000000,2745000000,1348000000
discontinuedOperations,None,None,None,None
netIncomeFromContinuingOps,55256000000,59531000000,48351000000,45687000000
netIncomeApplicableToCommonShares,55256000000,59531000000,48351000000,45687000000

In [42]:
transposed = income_statement.transpose()
transposed

Breakdown,researchDevelopment,effectOfAccountingCharges,incomeBeforeTax,minorityInterest,netIncome,sellingGeneralAdministrative,grossProfit,ebit,operatingIncome,otherOperatingExpenses,...,nonRecurring,otherItems,incomeTaxExpense,totalRevenue,totalOperatingExpenses,costOfRevenue,totalOtherIncomeExpenseNet,discontinuedOperations,netIncomeFromContinuingOps,netIncomeApplicableToCommonShares
endDate,,,,,,,,,,,,,,,,,,,,,
2019-09-28,16217000000,None,65737000000,None,55256000000,18245000000,98392000000,63930000000,63930000000,None,...,None,None,10481000000,260174000000,196244000000,161782000000,1807000000,None,55256000000,55256000000
2018-09-29,14236000000,None,72903000000,None,59531000000,16705000000,101839000000,70898000000,70898000000,None,...,None,None,13372000000,265595000000,194697000000,163756000000,2005000000,None,59531000000,59531000000
2017-09-30,11581000000,None,64089000000,None,48351000000,15261000000,88186000000,61344000000,61344000000,None,...,None,None,15738000000,229234000000,167890000000,141048000000,2745000000,None,48351000000,48351000000
2016-09-24,10045000000,None,61372000000,None,45687000000,14194000000,84263000000,60024000000,60024000000,None,...,None,None,15685000000,215639000000,155615000000,131376000000,1348000000,None,45687000000,45687000000

“ttm” stands for Trailing Twelve Months and typically shows either the most recent twelve months of a company’s operations or the last twelve months before a major event- like an acquisition

In [43]:
#How do I download data from the balance sheet?
balance_sheet = si.get_balance_sheet("aapl")
balance_sheet

endDate,2019-09-28,2018-09-29,2017-09-30,2016-09-24
Breakdown,,,,
totalLiab,2.480280e+11,2.585780e+11,2.412720e+11,1.934370e+11
totalStockholderEquity,9.048800e+10,1.071470e+11,1.340470e+11,1.282490e+11
otherCurrentLiab,4.324200e+10,3.929300e+10,3.809900e+10,8.243000e+09
totalAssets,3.385160e+11,3.657250e+11,3.753190e+11,3.216860e+11
commonStock,4.517400e+10,4.020100e+10,3.586700e+10,3.125100e+10
otherCurrentAssets,1.235200e+10,1.208700e+10,1.393600e+10,8.283000e+09
retainedEarnings,4.589800e+10,7.040000e+10,9.833000e+10,9.636400e+10
otherLiab,5.050300e+10,4.891400e+10,4.325100e+10,3.900400e+10
treasuryStock,-5.840000e+08,-3.454000e+09,-1.500000e+08,6.340000e+08
otherAssets,3.297800e+10,2.228300e+10,1.817700e+10,8.757000e+09
cash,4.884400e+10,2.591300e+10,2.028900e+10,2.048400e+10
totalCurrentLiabilities,1.057180e+11,1.159290e+11,1.008140e+11,7.900600e+10
shortLongTermDebt,1.026000e+10,8.784000e+09,6.496000e+09,3.500000e+09
otherStockholderEquity,-5.840000e+08,-3.454000e+09,-1.500000e+08,6.340000e+08
propertyPlantEquipment,3.737800e+10,4.130400e+10,3.378300e+10,2.701000e+10
totalCurrentAssets,1.628190e+11,1.313390e+11,1.286450e+11,1.068690e+11
longTermInvestments,1.053410e+11,1.707990e+11,1.947140e+11,1.704300e+11
netTangibleAssets,9.048800e+10,1.071470e+11,1.340470e+11,1.196290e+11
shortTermInvestments,5.171300e+10,4.038800e+10,5.389200e+10,4.667100e+10
netReceivables,4.580400e+10,4.899500e+10,3.567300e+10,2.929900e+10
longTermDebt,9.180700e+10,9.373500e+10,9.720700e+10,7.542700e+10
inventory,4.106000e+09,3.956000e+09,4.855000e+09,2.132000e+09
accountsPayable,4.623600e+10,5.588800e+10,4.424200e+10,3.729400e+10
intangibleAssets,NaN,NaN,NaN,3.206000e+09
goodWill,NaN,NaN,NaN,5.414000e+09

In [44]:
# How do I download data from the cashflow statement?
cash_flow_statement = si.get_cash_flow("aapl")
cash_flow_statement

endDate,2019-09-28,2018-09-29,2017-09-30,2016-09-24
Breakdown,,,,
investments,58093000000,30845000000,-33542000000,-32022000000
changeToLiabilities,-2548000000,9172000000,8373000000,563000000
totalCashflowsFromInvestingActivities,45896000000,16066000000,-46446000000,-45977000000
netBorrowings,-7819000000,432000000,29014000000,22057000000
totalCashFromFinancingActivities,-90976000000,-87876000000,-17974000000,-20890000000
changeToOperatingActivities,-896000000,30016000000,-8480000000,-902000000
issuanceOfStock,781000000,669000000,555000000,495000000
netIncome,55256000000,59531000000,48351000000,45687000000
changeInCash,24311000000,5624000000,-195000000,-636000000
repurchaseOfStock,-69714000000,-75265000000,-34774000000,-31292000000
totalCashFromOperatingActivities,69391000000,77434000000,64225000000,66231000000
depreciation,12547000000,10903000000,10157000000,10505000000
otherCashflowsFromInvestingActivities,-1078000000,-745000000,-124000000,-924000000
dividendsPaid,-14119000000,-13712000000,-12769000000,-12150000000
changeToInventory,-289000000,828000000,-2723000000,217000000
changeToAccountReceivables,245000000,-5322000000,-2093000000,527000000
otherCashflowsFromFinancingActivities,-105000000,-105000000,-105000000,-105000000
changeToNetincome,5076000000,-27694000000,10640000000,9634000000
capitalExpenditures,-10495000000,-13313000000,-12451000000,-12734000000

## How do I download options data?

So far we’ve only been using the stock_info module, now finally we will have a little play with the options module.

In [45]:
import yahoo_fin.options as ops

Briefly, options are contracts giving a trader the right, but not the obligation, to buy (call) or sell (put) the underlying asset they represent at a specific price on or before a certain date.

In [46]:
# How do I get Expiration dates?
expiration_dates = ops.get_expiration_dates("aapl")
expiration_dates

['July 31, 2020',
 'August 7, 2020',
 'August 14, 2020',
 'August 21, 2020',
 'August 28, 2020',
 'September 4, 2020',
 'September 18, 2020',
 'October 16, 2020',
 'November 20, 2020',
 'December 18, 2020',
 'January 15, 2021',
 'June 18, 2021',
 'September 17, 2021',
 'January 21, 2022',
 'June 17, 2022',
 'September 16, 2022']

Note that the following functions all take an optional Expiration Date parameter, but it should be given in the form ‘mm/dd/yyyy’, so you will have to do a bit of conversion if you want to use a specific date

In [47]:
# How do I get Calls Data?
ops.get_calls("aapl")

,Contract Name,Last Trade Date,Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility
0,AAPL200731C00170000,2020-07-29 9:44AM EDT,170.0,205.78,0.0,0.00,0.0,-,2,0,0.00%
1,AAPL200731C00175000,2020-06-18 3:59PM EDT,175.0,176.85,209.1,211.65,0.0,-,-,1,752.73%
2,AAPL200731C00180000,2020-07-23 2:23PM EDT,180.0,191.60,0.0,0.00,0.0,-,-,0,0.00%
3,AAPL200731C00185000,2020-07-06 3:30PM EDT,185.0,188.38,0.0,0.00,0.0,-,1,0,0.00%
4,AAPL200731C00190000,2020-06-24 9:58AM EDT,190.0,173.70,178.4,182.90,0.0,-,-,1,0.00%
...,...,...,...,...,...,...,...,...,...,...,...
86,AAPL200731C00530000,2020-07-29 12:54PM EDT,530.0,0.01,0.0,0.00,0.0,-,3,0,50.00%
87,AAPL200731C00540000,2020-07-27 1:51PM EDT,540.0,0.01,0.0,0.00,0.0,-,83,0,50.00%
88,AAPL200731C00550000,2020-07-29 2:17PM EDT,550.0,0.01,0.0,0.00,0.0,-,1,0,50.00%
89,AAPL200731C00560000,2020-07-27 11:34AM EDT,560.0,0.01,0.0,0.00,0.0,-,15,0,50.00%
90,AAPL200731C00570000,2020-07-28 2:35PM EDT,570.0,0.01,0.0,0.00,0.0,-,4,0,50.00%

In [48]:
# How do I get Puts Data?
ops.get_puts("aapl", "09/16/2022")

,Contract Name,Last Trade Date,Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility
0,AAPL220916P00160000,2020-07-29 12:11PM EDT,160.0,6.00,0.0,0.0,0.0,-,5,0,12.50%
1,AAPL220916P00165000,2020-07-14 11:00AM EDT,165.0,5.75,0.0,0.0,0.0,-,1,0,12.50%
2,AAPL220916P00170000,2020-07-21 1:55PM EDT,170.0,6.90,0.0,0.0,0.0,-,10,0,12.50%
3,AAPL220916P00175000,2020-07-29 10:36AM EDT,175.0,7.45,0.0,0.0,0.0,-,1,0,12.50%
4,AAPL220916P00180000,2020-07-29 10:36AM EDT,180.0,8.01,0.0,0.0,0.0,-,1,0,12.50%
5,AAPL220916P00185000,2020-07-28 12:03PM EDT,185.0,8.65,0.0,0.0,0.0,-,20,0,12.50%
6,AAPL220916P00190000,2020-07-24 10:50AM EDT,190.0,10.26,0.0,0.0,0.0,-,2,0,12.50%
7,AAPL220916P00195000,2020-07-24 9:30AM EDT,195.0,11.00,0.0,0.0,0.0,-,1,0,6.25%
8,AAPL220916P00200000,2020-07-24 9:40AM EDT,200.0,12.50,0.0,0.0,0.0,-,1,0,6.25%
9,AAPL220916P00210000,2020-07-15 10:30AM EDT,210.0,12.70,0.0,0.0,0.0,-,2,0,6.25%
10,AAPL220916P00220000,2020-07-20 12:01PM EDT,220.0,14.80,0.0,0.0,0.0,-,1,0,6.25%
11,AAPL220916P00230000,2020-07-23 3:11PM EDT,230.0,16.90,0.0,0.0,0.0,-,6,0,6.25%
12,AAPL220916P00240000,2020-07-28 3:29PM EDT,240.0,20.50,0.0,0.0,0.0,-,2,0,6.25%
13,AAPL220916P00250000,2020-07-29 2:21PM EDT,250.0,19.25,0.0,0.0,0.0,-,7,0,6.25%
14,AAPL220916P00260000,2020-07-24 11:30AM EDT,260.0,25.70,0.0,0.0,0.0,-,1,0,6.25%
15,AAPL220916P00270000,2020-07-24 11:30AM EDT,270.0,28.65,0.0,0.0,0.0,-,1,0,6.25%
16,AAPL220916P00280000,2020-07-24 3:59PM EDT,280.0,30.50,0.0,0.0,0.0,-,52,0,3.13%
17,AAPL220916P00290000,2020-07-13 10:05AM EDT,290.0,29.70,0.0,0.0,0.0,-,2,0,3.13%
18,AAPL220916P00300000,2020-07-28 12:03PM EDT,300.0,36.50,0.0,0.0,0.0,-,1,0,3.13%
19,AAPL220916P00305000,2020-07-13 2:50PM EDT,305.0,35.00,0.0,0.0,0.0,-,5,0,3.13%
20,AAPL220916P00310000,2020-07-23 2:27PM EDT,310.0,41.55,0.0,0.0,0.0,-,2,0,3.13%
21,AAPL220916P00315000,2020-07-10 11:18AM EDT,315.0,39.92,0.0,0.0,0.0,-,1,0,3.13%
22,AAPL220916P00320000,2020-07-24 12:39PM EDT,320.0,46.92,0.0,0.0,0.0,-,2,0,3.13%
23,AAPL220916P00325000,2020-07-29 3:36PM EDT,325.0,44.10,0.0,0.0,0.0,-,4,0,1.56%
24,AAPL220916P00330000,2020-07-24 12:39PM EDT,330.0,51.32,0.0,0.0,0.0,-,5,0,1.56%
25,AAPL220916P00335000,2020-07-27 3:02PM EDT,335.0,50.00,0.0,0.0,0.0,-,1,0,1.56%
26,AAPL220916P00340000,2020-07-22 10:27AM EDT,340.0,49.50,0.0,0.0,0.0,-,20,0,1.56%
27,AAPL220916P00345000,2020-07-23 12:53PM EDT,345.0,53.66,0.0,0.0,0.0,-,15,0,1.56%
28,AAPL220916P00350000,2020-07-29 2:45PM EDT,350.0,56.00,0.0,0.0,0.0,-,2,0,1.56%
29,AAPL220916P00360000,2020-07-29 10:23AM EDT,360.0,61.25,0.0,0.0,0.0,-,10,0,0.78%
30,AAPL220916P00370000,2020-07-24 3:13PM EDT,370.0,69.40,0.0,0.0,0.0,-,3,0,0.39%
31,AAPL220916P00380000,2020-07-23 2:05PM EDT,380.0,71.00,0.0,0.0,0.0,-,10,0,0.01%
32,AAPL220916P00390000,2020-07-24 10:16AM EDT,390.0,84.00,0.0,0.0,0.0,-,1,0,0.00%
33,AAPL220916P00400000,2020-07-29 2:22PM EDT,400.0,83.00,0.0,0.0,0.0,-,1,0,0.00%
34,AAPL220916P00410000,2020-07-13 9:34AM EDT,410.0,85.40,0.0,0.0,0.0,-,-,0,0.00%
35,AAPL220916P00420000,2020-07-27 3:59PM EDT,420.0,96.00,0.0,0.0,0.0,-,1,0,0.00%
36,AAPL220916P00430000,2020-06-23 11:39AM EDT,430.0,106.00,105.3,109.0,0.0,-,-,0,35.04%
37,AAPL220916P00450000,2020-07-09 2:28PM EDT,450.0,112.12,0.0,0.0,0.0,-,1,0,0.00%
38,AAPL220916P00460000,2020-07-13 10:10AM EDT,460.0,111.10,0.0,0.0,0.0,-,3,0,0.00%
39,AAPL220916P00500000,2020-07-23 12:06PM EDT,500.0,151.00,0.0,0.0,0.0,-,1,0,0.00%
40,AAPL220916P00520000,2020-07-14 10:13AM EDT,520.0,168.51,0.0,0.0,0.0,-,20,0,0.00%
41,AAPL220916P00540000,2020-07-28 2:12PM EDT,540.0,186.00,0.0,0.0,0.0,-,40,0,0.00%
42,AAPL220916P00560000,2020-07-08 10:53AM EDT,560.0,196.95,0.0,0.0,0.0,-,-,0,0.00%